myapp/wolves/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class WolvesForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

myapp/core/views.py
# core/views.py 

from flask import render_template, request, Blueprint
from myapp.models import Wolves

core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    wolves = Wolves.query.order_by(Wolves.date.desc()).paginate(page=page, per_page=6)
    return render_template('index.html', wolves=wolves)

@core.route('/info')
def info():
    return render_template('info.html')

myapp/users/views.py
from crypt import methods
from operator import methodcaller
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myapp import db
from myapp.models import User, Wolves
from myapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint('users', __name__) # dont forget to register this in __init__.py 


# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index')) #once the user has logged out we will redirect them back home


#account (update UserForm)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit(): 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User account updated!!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('account.html', form=form)

@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    wolves = Wolves.query.filter_by(author=user).order_by(Wolves.date.desc()).paginate(page=page, per_page=4) 
    return render_template('user_wolves.html', wolves=wolves, user=user)

myapp/wolves/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import Wolves
from myapp.wolves.forms import WolvesForm

wolves_posts = Blueprint('wolves_posts', __name__)

@wolves_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = WolvesForm()
    if form.validate_on_submit():
        wolf = Wolves(title=form.title.data, text=form.text.data, user_id=current_user.id)
        db.session.add(wolf)
        db.session.commit()
        flash('Wolf Created')
        print('Your Wolf was created')
        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)

# Make sure the wolves_id is an integer!

@wolves_posts.route('/<int:wolves_id>')
def wolf(wolves_id):
    wolf = Wolves.query.get_or_404(wolves_id) 
    return render_template('wolves.html', title=wolf.title, date=wolf.date, post=wolf)

@wolves_posts.route('/<int:wolves_id>/update',methods=['GET','POST'])
@login_required
def update(wolves_id):
    wolf = Wolves.query.get_or_404(wolves_id)

    if wolf.author != current_user:
        abort(403)

    form = WolvesForm()

    if form.validate_on_submit():
        wolf.title = form.title.data
        wolf.text = form.text.data
        db.session.commit()
        flash('Wolf Updated')
        return redirect(url_for('wolves_posts.wolf',wolves_id=wolf.id))

    elif request.method == 'GET':
        form.title.data = wolf.title
        form.text.data = wolf.text

    return render_template('create_post.html',title='Updating',form=form)

@wolves_posts.route('/<int:wolves_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(wolves_id):

    wolf = Wolves.query.get_or_404(wolves_id)
    if wolf.author != current_user:
        abort(403)

    db.session.delete(wolf)
    db.session.commit()
    flash('Wolf Deleted')
    return redirect(url_for('core.index'))

myapp/templates/account.html
{% extends "base.html" %}
{% block content %}
   
<link rel="stylesheet" href="{{ url_for('static', filename= 'style/account.css')}}">

<div class="center-title">
    <div class="title">
        <h1>Account page for {{current_user.username}}</h1>
    </div>
</div>

<div class="center-container">
    <div class="container">
        <form method="POST" action="" enctype="multipart/form-data">
                {{form.hidden_tag()}}
                {{form.username.label}}</br>
                {{form.username}}</br>
                {{form.email.label}}</br>
                {{form.email}}

            <div class="submit">
                {{form.submit}}
            </div>
        </form>
    </div>
</div>

{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="{{ url_for('static', filename= 'style/base.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'style/background.css')}}">
    <script defer src="{{ url_for('static', filename= 'js/hamburger.js')}}"></script>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wolf Collector</title>
</head>
<body>
    <nav class="navbar">
        <div class="brand-title">Wolf Collector</div>
        <a href="#" class="toggle-btn">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </a>
        <div class="navbar-links">
            <ul>
                <li>
                    <a href="{{url_for('core.index')}}">Home</a>
                </li>
                <li>
                    <a href="{{url_for('core.info')}}">About</a>
                </li>

                {% if current_user.is_authenticated %}
                <li>
                    <a href="{{url_for('wolves_posts.create_post')}}">Create Post</a> 
                </li>
                <li>
                    <a href="{{url_for('users.account')}}">Account</a>
                </li>
                <li>
                    <a href="{{url_for('users.logout')}}">Log Out</a>
                </li>
                {% else %}
                <li>
                    <a href="{{url_for('users.login')}}">Log In</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div>
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

myapp/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename= 'style/create.css')}}">

<div class="center-container">
  <div class="title-body">
    <h1>Create Your Wolf</h1>
  </div>
    <div class="container">
      <form method="POST">
          {{form.hidden_tag()}}
          <div>
              <p>Name:</p>
              {{form.title}}
          </div>
          <div>
            <p>Description:</p>
            {{form.text(class="description")}}
        </div>
        <div>
            {{form.submit}}
        </div>
      </form>
    </div>
    <img src="../static/img/wolf-create-img.jpg">
  </div>
{% endblock %}

myapp/templates/index.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename= 'style/index.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename= 'style/img.css')}}">
<script defer src="{{ url_for('static', filename= 'js/rando-pictures.js')}}"></script>

<div class="center-title">
    <div class="title-body">
        <h1>The Wolves Are Here</h1>
    </div>
</div>

    <div class="container">
        {% for post in wolves.items %}
            <div class="card">
                <div>
                    <img class="random-wolf" src="">
                    <h2 class="wolf-name">
                        <a class="card-title" href="{{url_for('wolves_posts.wolf', wolves_id=post.id)}}">{{post.title}}</a>
                    </h2>
                    <p class="content">
                        <a href="{{url_for('users.user_posts', username=post.author.username)}}">Owner: {{post.author.username}}</a>
                    </p>
                    <p class="date">Published: {{post.date.strftime('%Y - %m - %d')}}</p>
                    <a class="content" href="{{url_for('wolves_posts.wolf', wolves_id=post.id)}}">Read About This Wolf</a>
                </div>
            </div>
        {% endfor %}
    </div>

    <nav class="page-nav">
        <ul class="page-nums">
            {% for page_num in wolves.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if wolves.page == page_num %}
                <li class="num">
                    <a href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="num">
                    <a href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>
{% endblock %}

myapp/templates/info.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename= 'style/info.css')}}">
<div class="center-title">
    <div class="title-body">
        <h1>What Is Wolf Collector?</h1>
    </div>
</div>
<div class="center-body">
    <div class="container">
        <p>
            Wolf Collector is a blog posting site used to keep track of pack members! Post the name and a description of your pack mate, then have a look at other pack members. See who, when, and why they were added to the pack!
        </p>
    </div>
    <img src="../static/img/wolf-pack.jpg">
</div>
{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}
{% block content %}
   
<link rel="stylesheet" href="{{ url_for('static', filename= 'style/login.css')}}">

<div class="center-container">
    <div class="container">
        <form method="POST">
            {{form.hidden_tag()}}
            {{form.email.label}}{{form.email}}<br>
            {{form.password.label}}{{form.password}}<br>
            <div class="submit-btn">
                {{form.submit()}}
            </div>

        </form>
        <div class="register">
            Dont have an account? 
            <a href="{{url_for('users.register')}}"> Register</a>
        </div>
    </div>
</div>
{% endblock %}

myapp/templates/register.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename= 'style/register.css')}}">

<div class="center-container">
    <div class="container">
        <form method="POST">
            {{form.hidden_tag()}}
            {{form.email.label}}{{form.email}}<br>
            {{form.username.label}}{{form.username}}<br>
            {{form.password.label}}{{form.password}}<br>
            {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
            <div class="submit-btn">
                {{form.submit()}}
            </div>
        </form>

            <div class="login">
                Already have an account? <a href="{{url_for('users.login')}}"> Log In</a>
            </div>
    </div>
</div>
{% endblock %}

myapp/templates/user_wolves.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename= 'style/user.css')}}">
<script defer src="{{ url_for('static', filename= 'js/rando-pictures.js')}}"></script>

<div class="center-title">
    <div class="title">
        <h1 class="first-title">Here is all of {{user.username}}'s pack mates!</h1>
        <h1 class="second-title">{{user.username}}'s pack mates!</h1>
    </div>
</div>
<div class="center-container">
    <div class="container">
        {% for post in wolves.items %}
        <div class="card">
            <img class="random-wolf" src="">
            <h2>
                <a href="{{url_for('wolves_posts.wolf', wolves_id=post.id)}}">{{post.title}}</a>
            </h2>
            Written By: <a href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username}}</a>

            <p>
                Published On: {{post.date.strftime("%y-%m-%d")}}
            </p><br>
            <p class="post-text">{{post.text}}</p><br>
        </div>
        {% endfor %}
    </div>
</div>
    <nav class="page-nav">
        <ul class="page-nums">
            {% for page_num in wolves.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if wolves.page == page_num %}
                <li class="num">
                    <a href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="num">
                    <a href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>


{% endblock %}

myapp/templates/wolves.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename= 'style/wolves.css')}}">
<script defer src="{{ url_for('static', filename= 'js/rando-pictures.js')}}"></script>

<div class="center-container">
  <div class="container">
    <img src="" class="random-wolf">
    <h1>{{ post.title }}</h1>
    <h2>Written by: {{post.author.username}}</h2>
    <h3 class="date">Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
    <p class="post-text">{{post.text}}</p>
    {% if post.author == current_user %}
  </div>
</div>
<div class="center-btns">
    <div class="btns">
      <div class="update-btn">
        <a href="{{ url_for('wolves_posts.update', wolves_id=post.id) }}">Update</a>
      </div>
      <div>
        <form action="{{ url_for('wolves_posts.delete_post', wolves_id=post.id) }}" method="POST">
          <input class="del-btn" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
    {% endif %}
{% endblock content %}